import Order from '../models/order';
import { findJetById } from './jet';
// CRUD Operations for Jet
export const createOneOrder = async (userId, jetId) => {
    try {
        // 1. Find the jet model to get its current price
        const jetTemplate = await findJetById(jetId);
        if (!jetTemplate) {
            throw new Error("The jet model you are trying to buy does not exist.");
        }
        const newOrderData = new Order({
            user: userId,
            jet: jetId,
            totalPrice: jetTemplate.price, // Snapshot of the price now
            status: 'pending'
            // instanceSerialNumber is generated by the Schema's default function
        });

        // 2. Create the Order (The "Simple Instance")
        const createdOrder = await Order.insertOne(newOrderData);
        return createdOrder;
    } catch (e) {
        return null;
    }
}

/**
 * Update order status using the Serial Number
 */
export const updateOrderBySerial = async (serialNumber, newStatus) => {
    try {
        // We use findOneAndUpdate to find the specific serial number
        const updatedOrder = await Order.findOneAndUpdate(
            { instanceSerialNumber: serialNumber }, 
            { status: newStatus }, 
            { new: true } 
        ).populate('user jet');
        // Take the Jet off the market
        await Jet.findByIdAndUpdate(updatedOrder.jet, { isAvailable: false });
        return updatedOrder;
    } catch (e) {
        console.error("Error updating order by serial:", e);
        return null;
    }
}